export { ServiceError, isServiceError, serviceError } from "@/services/errors"
export type { ServiceContext, StoreServiceContext, NegocioServiceContext } from "@/services/context"
export { toServiceResponse, createdResponse, jsonSuccess } from "@/services/http"
export { ProductService, generateSku } from "@/services/product.service"
export type { ProductListOptions } from "@/services/product.service"
export { InventoryService } from "@/services/inventory.service"
export type { StockMovementListOptions } from "@/services/inventory.service"
export { CustomerService } from "@/services/customer.service"
export type { CustomerListOptions, CustomerFindOrCreateInput } from "@/services/customer.service"
export { AgendaService } from "@/services/agenda.service"
export type { AppointmentListOptions, AppointmentCreateInput } from "@/services/agenda.service"
export { OrderService } from "@/services/order.service"
export type { OrderListOptions } from "@/services/order.service"
export { SalesService } from "@/services/sales.service"
export type { SalesSummaryOptions } from "@/services/sales.service"
